name: Blog Deploy deno
on:
    push:
        branches:
            - publish

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'TianMengLucky'
        permissions:
            id-token: write # Needed for auth with Deno Deploy
            contents: read # Needed to clone the repository

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            
            -   name: Install PackageManager
                uses: pnpm/action-setup@v4
            
            -   name: Install Node
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: pnpm
                    cache-dependency-path: ./pnpm-lock.yaml
            
            -   name: Install Dependencies
                shell: "bash"
                run: pnpm install

            -   name: Build
                shell: "bash"
                run: pnpm build:deno
            
            -   name: Upload to Deno Deploy
                uses: denoland/deployctl@v1
                with:
                    project: tian-meng-blog
                    entrypoint: jsr:@std/http/file-server
                    root: dist